# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories true

set tclUtilsPath "c:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "C:/Users/vsilantiev/Documents/WRAPPERFORAC701/project_3/project_3.srcs/sources_1/ip/cg_nt_index_map.xml"

set cgProjectPath "c:/Users/vsilantiev/Documents/WRAPPERFORAC701/ipcore_dir/coregen.cgc"

set ipFile "c:/Users/vsilantiev/Documents/WRAPPERFORAC701/ipcore_dir/v6_sfifo_15x128.xco"

set ipName "v6_sfifo_15x128"

set hdlType "VHDL"

set cgPartSpec "xc7a200t-2fbg676"

set chains "GENERATE_CURRENT_CHAIN"

set params ""

set bomFilePath "c:/Users/vsilantiev/Documents/WRAPPERFORAC701/ipcore_dir/pa_cg_bom.xml"

# generate the IP
set result [source "c:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_gen_out_prods.tcl"]

exit $result

