# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories false

set tclUtilsPath "c:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "C:/Users/vsilantiev/Documents/WRAPPERFORAC701/project_1/project_1.srcs/sources_1/ip/cg_nt_index_map.xml"

set cgProjectPath "c:/Users/vsilantiev/Documents/WRAPPERFORAC701/ipcore_dir_ISE13.3/coregen.cgc"

set ipFile "c:/Users/vsilantiev/Documents/WRAPPERFORAC701/ipcore_dir_ISE13.3/v6_mBuf_128x72.xco"

set ipName "v6_mBuf_128x72"

set hdlType "VHDL"

set cgPartSpec "xc7a200t-2fbg676"

set chains "GENERATE_CURRENT_CHAIN"

set params ""

set bomFilePath "c:/Users/vsilantiev/Documents/WRAPPERFORAC701/ipcore_dir_ISE13.3/pa_cg_bom.xml"

# generate the IP
set result [source "c:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_gen_out_prods.tcl"]

exit $result

