# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories false

set tclUtilsPath "c:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "C:/Users/vsilantiev/Documents/WRAPPERFORAC701/project_3/project_3.srcs/sources_1/ip/cg_nt_index_map.xml"

set cgProjectPath "c:/Users/vsilantiev/Documents/WRAPPERFORAC701/v6_mBuf_128x72/coregen.cgc"

set ipFile "c:/Users/vsilantiev/Documents/WRAPPERFORAC701/v6_mBuf_128x72/v6_mBuf_128x72.xco"

set ipName "v6_mBuf_128x72"

set chains "CUSTOMIZE_CURRENT_CHAIN INSTANTIATION_TEMPLATES_CHAIN"

set bomFilePath "c:/Users/vsilantiev/Documents/WRAPPERFORAC701/v6_mBuf_128x72/pa_cg_bom.xml"

set cgPartSpec "xc7a200t-2fbg676"

set hdlType "VHDL"

# generate the IP
set result [source "c:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_reconfig_core.tcl"]

exit $result

